### ISSUE TITLE
Unused Argument

### ISSUE THREAD

**Issue by SoapKe** [ysun647/Nucleus#10]
Many arguments are unused after defined.

************* Module util.py
W: 47,46: Unused argument 'context_char_idxs' (unused-argument)
W: 47,89: Unused argument 'qa_id' (unused-argument)
W: 47,65: Unused argument 'ques_char_idxs' (unused-argument)
W: 47,81: Unused argument 'y1' (unused-argument)
W: 47,85: Unused argument 'y2' (unused-argument)
W: 47,35: Unused argument 'ques_idxs' (unused-argument)
W: 57,24: Unused argument 'key' (unused-argument)

************* Module prepro.py
W:127,29: Unused argument 'is_test' (unused-argument)

************* Module func.py
W:  8,100: Unused argument 'scope' (unused-argument)

**Comment by mryimings** [comment]
not sure which file contains these errors. if you mean r_net: the r_net is now deprecated. Please try bert in our most up-to-date version
