### ISSUE TITLE
Too many local variables

### ISSUE THREAD

**Issue by SoapKe** [ysun647/Nucleus#12]
Too many local variables used when a function or method has too many local variables.

************* Module func.py
R:  8, 4: Too many local variables (16/15) (too-many-locals)
R: 29, 4: Too many local variables (19/15) (too-many-locals)
R: 55, 4: Too many local variables (16/15) (too-many-locals)
R: 77, 4: Too many local variables (19/15) (too-many-locals)
R:167, 0: Too many local variables (18/15) (too-many-locals)

************* Module main.py
R: 11, 0: Too many local variables (35/15) (too-many-locals)
R: 93, 0: Too many local variables (19/15) (too-many-locals)
R:115, 0: Too many local variables (23/15) (too-many-locals)

************* Module inference.py
R: 65, 4: Too many local variables (30/15) (too-many-locals)
R:149, 4: Too many local variables (19/15) (too-many-locals)

************* Module model.py
R: 57, 4: Too many local variables (33/15) (too-many-locals)

************* Module prepro.py
R: 31, 0: Too many local variables (34/15) (too-many-locals)
R: 83, 0: Too many local variables (23/15) (too-many-locals)
R:121, 0: Too many local variables (31/15) (too-many-locals)
R:204, 0: Too many local variables (20/15) (too-many-locals)

**Comment by mryimings** [comment]
we believe local variable is important in deep learning, and it is unrealistic to have only 15 local vars in one file
