### ISSUE TITLE
bad operand type for unary -: NoneType

### ISSUE THREAD

**Issue by Zefeng-Liu** [ysun647/Nucleus#16]
E: 93,39: bad operand type for unary -: NoneType (invalid-unary-operand-type)
```
def get_embedding(counter, data_type, limit=-1, emb_file=None, size=None, vec_size=None, token2idx_dict=None):
    ...
    for line in tqdm(fh, total=size):
        array = line.split()
        word = ''.join(array[0:-vec_size])
        vector = list(map(float, array[-vec_size:]))
    ...
```
vec_size is an argument with default value None, use a None value in array alice with unary - is not good code, although they have an assert prior to this, the arguments list should be repacked and formatted.

**Comment by mryimings** [comment]
emmm vec_size is not a nontype :)
