### ISSUE TITLE
Invalid unary operand type

### ISSUE THREAD

**Issue by SoapKe** [ysun647/Nucleus#17]
************* Module prepro.py
E: 93,39: bad operand type for unary -: NoneType (invalid-unary-operand-type)
E: 94,47: bad operand type for unary -: NoneType (invalid-unary-operand-type)

...
                word = ''.join(array[0:-vec_size])
                vector = list(map(float, array[-vec_size:]))
...

**Comment by mryimings** [comment]
emmm we believe this is now a grammatical problem. Can you run this file anyway?
