### ISSUE TITLE
Include Version Numbers in "requirements.txt" Files

### ISSUE THREAD

**Issue by seungbineleanor** [ysun647/Nucleus#18]
Due to the sensitivity of packages in deep learning projects to version number (especially Tensorflow), I would highly recommend including version numbers in the `requirements.txt` files to ensure that everything will work in the future.  The author of the R-Net implementation that you're using even states: ["There have been a lot of known problems caused by using different software versions."](https://github.com/HKUST-KnowComp/R-Net)  For reference, the Tensorflow downloaded via the root `requirements.txt` on my machine is 1.12.0, and it appears that the original author tested his/her implementation with 1.5.0, so there is a high probability that some of the code he/she wrote will be deprecated in a newer Tensorflow version in the near future.

**Comment by mryimings** [comment]
will try to include them in the future
