### ISSUE TITLE
Update README and Include Trained Model

### ISSUE THREAD

**Issue by alekzieba** [ysun647/Nucleus#19]
It would probably be worth updating the root README to provide more specific steps as to how to train and test the R-Net model to avoid any confusion.  Additionally, including the trained model that you used would allow us to reproduce your test results with complete certainty and would save us from training the model ourselves.  You can do so in a release like the original author did [here](https://github.com/HKUST-KnowComp/R-Net/releases).  If you'd rather include a link to the original author's trained model, you could add that to the root README and include steps as to how to use it within the project.  To that end, including a link to the original model repo is probably a good idea too.

**Comment by mryimings** [comment]
we updated the readme with a bert model, and now it is available to download
