### ISSUE TITLE
No-name-in-module

### ISSUE THREAD

**Issue by LEE0816** [ysun647/Nucleus#2]
The file config.py doesn’t have the ‘cognito_userpool_id’ and 'cognito_app_client_id', but it is imported in the file application.py, which may raise the error. It is needed to define these two variables in config.py before it is imported.

**Comment by Michaellee955** [comment]
Thanks for the advice. The file config.py, which is under root directory, contains all our keys and tokens. We just gitignore it to avoid any privacy issue.

**Comment by mryimings** [comment]
Just as Minghao Said
