### ISSUE TITLE
Change Data Download Directory

### ISSUE THREAD

**Issue by alekzieba** [ysun647/Nucleus#20]
Right now, the R-Net model code saves training data within the `~/data` directory no matter where the code is on the system.  It would probably be worth changing the code to make the data be saved within the project itself because this current approach is unconventional and can lead to unexpected errors if another program were to modify this directory.

**Comment by alekzieba** [comment]
The files that control this are `models/r_net/download.sh` and `models/r_net/config.py`, I believe.

**Comment by mryimings** [comment]
the r_net is noe deprecated, please try our new model bert
