### ISSUE TITLE
Line too long

### ISSUE THREAD

**Issue by SoapKe** [ysun647/Nucleus#3]
According to the pylint result, there are many lines in the project that are considered too long, which are longer than 100 characters.

************* Module db_update_class.py
C:  8, 0: Line too long (113/100) (line-too-long)
C: 44, 0: Line too long (103/100) (line-too-long)
C: 54, 0: Line too long (119/100) (line-too-long)
C: 83, 0: Line too long (120/100) (line-too-long)
C: 93, 0: Line too long (103/100) (line-too-long)
C: 98, 0: Line too long (103/100) (line-too-long)

************* Module test_inference.py
C: 11, 0: Line too long (108/100) (line-too-long)

************* Module test_database.py
C:105, 0: Line too long (116/100) (line-too-long)

************* Module util.py
C: 17, 0: Line too long (102/100) (line-too-long)

************* Module prepro.py
C: 73, 0: Line too long (124/100) (line-too-long)
C: 77, 0: Line too long (102/100) (line-too-long)
C: 83, 0: Line too long (110/100) (line-too-long)
C:121, 0: Line too long (103/100) (line-too-long)
C:128, 0: Line too long (102/100) (line-too-long)
C:182, 0: Line too long (131/100) (line-too-long)
C:183, 0: Line too long (125/100) (line-too-long)
C:184, 0: Line too long (141/100) (line-too-long)
C:185, 0: Line too long (135/100) (line-too-long)
C:186, 0: Line too long (111/100) (line-too-long)
C:187, 0: Line too long (111/100) (line-too-long)
C:188, 0: Line too long (110/100) (line-too-long)
C:223, 0: Line too long (133/100) (line-too-long)
C:230, 0: Line too long (126/100) (line-too-long)

************* Module model.py
C: 59, 0: Line too long (153/100) (line-too-long)
C:105, 0: Line too long (105/100) (line-too-long)

************ Module inference.py
C: 48, 0: Line too long (104/100) (line-too-long)
C: 50, 0: Line too long (104/100) (line-too-long)
C: 60, 0: Line too long (107/100) (line-too-long)
C: 61, 0: Line too long (107/100) (line-too-long)
C: 66, 0: Line too long (109/100) (line-too-long)
C: 71, 0: Line too long (101/100) (line-too-long)
C: 72, 0: Line too long (101/100) (line-too-long)
C: 75, 0: Line too long (112/100) (line-too-long)
C: 78, 0: Line too long (112/100) (line-too-long)
C: 92, 0: Line too long (106/100) (line-too-long)
C: 98, 0: Line too long (107/100) (line-too-long)
C:103, 0: Line too long (109/100) (line-too-long)
C:114, 0: Line too long (119/100) (line-too-long)
C:141, 0: Line too long (105/100) (line-too-long)
C:143, 0: Line too long (120/100) (line-too-long)
C:197, 0: Line too long (1308/100) (line-too-long)

************* Module main.py
C: 65, 0: Line too long (104/100) (line-too-long)
C: 70, 0: Line too long (110/100) (line-too-long)

************* Module func.py
C:  8, 0: Line too long (112/100) (line-too-long)
C: 55, 0: Line too long (120/100) (line-too-long)
C: 86, 0: Line too long (104/100) (line-too-long)
C:167, 0: Line too long (101/100) (line-too-long)

************* Module application.py
C: 27, 0: Line too long (109/100) (line-too-long)
C: 45, 0: Line too long (102/100) (line-too-long)
C: 46, 0: Line too long (116/100) (line-too-long)
C: 61, 0: Line too long (115/100) (line-too-long)
C: 85, 0: Line too long (105/100) (line-too-long)

**Comment by mryimings** [comment]
We set the max length to 120 and we believe it is not a problem.
